version = 1

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["public_html/index.php"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "ember",
    "meteor",
    "angularjs",
    "angular"
  ]